# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mail.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_mailWindow(object):
    def setupUi(self, mailWindow):
        mailWindow.setObjectName("mailWindow")
        mailWindow.resize(464, 329)
        self.centralwidget = QtWidgets.QWidget(mailWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.welcomeLbl = QtWidgets.QLabel(self.centralwidget)
        self.welcomeLbl.setGeometry(QtCore.QRect(10, 0, 161, 31))
        self.welcomeLbl.setObjectName("welcomeLbl")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 30, 461, 301))
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.deleteBtn = QtWidgets.QPushButton(self.tab)
        self.deleteBtn.setGeometry(QtCore.QRect(180, 230, 94, 27))
        self.deleteBtn.setObjectName("deleteBtn")
        self.backBtn = QtWidgets.QPushButton(self.tab)
        self.backBtn.setGeometry(QtCore.QRect(10, 230, 94, 27))
        self.backBtn.setObjectName("backBtn")
        self.nextBtn = QtWidgets.QPushButton(self.tab)
        self.nextBtn.setGeometry(QtCore.QRect(350, 230, 94, 27))
        self.nextBtn.setObjectName("nextBtn")
        self.mailText = QtWidgets.QTextBrowser(self.tab)
        self.mailText.setGeometry(QtCore.QRect(10, 10, 441, 211))
        self.mailText.setObjectName("mailText")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.addressText = QtWidgets.QLineEdit(self.tab_2)
        self.addressText.setGeometry(QtCore.QRect(10, 10, 121, 27))
        self.addressText.setObjectName("addressText")
        self.sendBtn = QtWidgets.QPushButton(self.tab_2)
        self.sendBtn.setGeometry(QtCore.QRect(360, 230, 94, 27))
        self.sendBtn.setObjectName("sendBtn")
        self.letterText = QtWidgets.QTextEdit(self.tab_2)
        self.letterText.setGeometry(QtCore.QRect(10, 50, 431, 171))
        self.letterText.setObjectName("letterText")
        self.tabWidget.addTab(self.tab_2, "")
        mailWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(mailWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(mailWindow)

    def retranslateUi(self, mailWindow):
        _translate = QtCore.QCoreApplication.translate
        mailWindow.setWindowTitle(_translate("mailWindow", "Mail"))
        self.welcomeLbl.setText(_translate("mailWindow", "Приветствую, name!"))
        self.deleteBtn.setText(_translate("mailWindow", "Удалить"))
        self.backBtn.setText(_translate("mailWindow", "Назад"))
        self.nextBtn.setText(_translate("mailWindow", "Дальше"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("mailWindow", "Входящие"))
        self.sendBtn.setText(_translate("mailWindow", "Отправить"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("mailWindow", "Написать"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    mailWindow = QtWidgets.QMainWindow()
    ui = Ui_mailWindow()
    ui.setupUi(mailWindow)
    mailWindow.show()
    sys.exit(app.exec_())
